version: '3.8'
services:
  slack-mock:
    image: wiremock/wiremock:latest
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock-mappings:/home/wiremock/mappings
      - ./wiremock-files:/home/wiremock/__files
    command: --global-response-templating --verbose --enable-browser-proxying
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  slack-websocket:
    build: .
    ports:
      - "8765:8765"
    depends_on:
      - slack-mock
    environment:
      - WIREMOCK_URL=http://slack-mock:8080
      - WEBSOCKET_PORT=8765
