#!/usr/bin/env python3
"""
Simple Threshold Demo - Shows 0.8 vs 0.95 threshold effect
"""

from ai_quality_validation import AIQualityValidator

def test_threshold_effect():
    """Test how different thresholds affect validation"""
    print("🎯 Threshold Effect Demo")
    print("=" * 40)
    
    # Create content that's similar but not identical to baseline
    test_content = """Daily Brief - 2024-01-15

Email Summary:
• Quarterly Sales Report - john@company.com  
• Client Meeting Request - sarah@client.com
• Invoice Payment Overdue - billing@vendor.com

Key Insights:
• 3 urgent items require immediate attention
• 2 client meetings scheduled for this week  
• 1 invoice payment overdue
• New project proposal received

Action Items:
• Review quarterly sales report
• Schedule follow-up meeting with client
• Process invoice payment
• Prepare project proposal

Generated by Person.ai"""

    print("📝 Test content:")
    print(f"   Length: {len(test_content)} chars")
    print(f"   Preview: {test_content[:80]}...")
    
    # Test with different thresholds
    thresholds = [0.8, 0.95]
    
    for threshold in thresholds:
        print(f"\n🧪 Testing with threshold: {threshold}")
        
        # Create custom validator with specific threshold
        class CustomValidator(AIQualityValidator):
            def _validate_semantic_similarity(self, content: str, content_type: str):
                baseline_key = f"{content_type}_baseline"
                if baseline_key not in self.baselines:
                    return {"score": 0.0, "passed": False, "details": "No baseline available"}
                
                baseline = self.baselines[baseline_key]
                similarity = self._calculate_similarity(content, baseline["content"])
                
                passed = similarity >= threshold
                
                return {
                    "score": similarity,
                    "passed": passed,
                    "details": f"Similarity: {similarity:.3f} (threshold: {threshold})",
                    "similarity": similarity,
                    "baseline_created": baseline["created_at"]
                }
        
        validator = CustomValidator()
        result = validator.validate_content_quality(test_content, "text")
        
        score = result['validations']['semantic_similarity']['score']
        passed = result['validations']['semantic_similarity']['passed']
        
        print(f"   Score: {score:.3f}")
        print(f"   Passed: {'✅ YES' if passed else '❌ NO'}")
        print(f"   Details: {result['validations']['semantic_similarity']['details']}")

if __name__ == "__main__":
    test_threshold_effect()
