services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - api
    environment:
      - API_BASE_URL=http://api:5000/api

  api:
    build: ./api
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - CORS_ORIGINS=http://localhost:8081

  test-runner:
    build: .
    depends_on:
      frontend:
        condition: service_healthy
      api:
        condition: service_healthy
    environment:
      - FRONTEND_URL=http://frontend:80
      - API_URL=http://api:5000/api
    volumes:
      - ./tests:/app/tests
      - ./visual_baselines:/app/visual_baselines
      - ./output:/app/output
