name: Simple CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # Test all Python components without Docker
  test-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [
          'slack-mock',
          'test-data-seeding', 
          'e2e-testing',
          'monitoring-system',
          'bubble-frontend-mock',
          'contract-testing'
        ]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        cd ${{ matrix.component }}
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        # Install pytest if not in requirements
        pip install pytest
    
    - name: Run tests
      run: |
        cd ${{ matrix.component }}
        if [ -d tests ]; then
          python3 -m pytest tests/ -v --tb=short
        else
          echo "No tests directory found for ${{ matrix.component }}"
        fi
    
    - name: Run demo scripts
      run: |
        cd ${{ matrix.component }}
        if [ -f scripts/quick_demo.py ]; then
          python3 scripts/quick_demo.py
        elif [ -f safe_integration.py ]; then
          python3 safe_integration.py
        else
          echo "No demo script found for ${{ matrix.component }}"
        fi
      continue-on-error: true
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.component }}-test-results
        path: ${{ matrix.component }}/
