name: Simple CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # Test all Python components without Docker
  test-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [
          'slack-mock',
          'test-data-seeding', 
          'e2e-testing',
          'monitoring-system',
          'bubble-frontend-mock',
          'contract-testing'
        ]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        cd ${{ matrix.component }}
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        # Install pytest if not in requirements
        pip install pytest
    
    - name: Run tests
      run: |
        cd ${{ matrix.component }}
        if [ -d tests ]; then
          # For test-data-seeding, run standalone tests first
          if [ "${{ matrix.component }}" = "test-data-seeding" ]; then
            python3 -m pytest tests/test_api_mocks_standalone.py -v --tb=short
            python3 -m pytest tests/test_data_generation.py -v --tb=short
          # For e2e-testing, run standalone tests first
          elif [ "${{ matrix.component }}" = "e2e-testing" ]; then
            python3 -m pytest tests/test_e2e_standalone.py -v --tb=short
          # For monitoring-system, run standalone tests first
          elif [ "${{ matrix.component }}" = "monitoring-system" ]; then
            python3 -m pytest tests/test_monitoring_standalone.py -v --tb=short
          # For slack-mock, run standalone tests first
          elif [ "${{ matrix.component }}" = "slack-mock" ]; then
            python3 -m pytest tests/test_slack_standalone.py -v --tb=short
          # For bubble-frontend-mock, run standalone tests first
          elif [ "${{ matrix.component }}" = "bubble-frontend-mock" ]; then
            python3 -m pytest tests/test_bubble_standalone.py -v --tb=short
          # For contract-testing, run standalone tests first
          elif [ "${{ matrix.component }}" = "contract-testing" ]; then
            python3 -m pytest tests/test_contract_standalone.py -v --tb=short
          else
            python3 -m pytest tests/ -v --tb=short
          fi
        else
          echo "No tests directory found for ${{ matrix.component }}"
        fi
    
    - name: Run demo scripts
      run: |
        cd ${{ matrix.component }}
        if [ -f scripts/quick_demo.py ]; then
          python3 scripts/quick_demo.py
        elif [ -f safe_integration.py ]; then
          python3 safe_integration.py
        else
          echo "No demo script found for ${{ matrix.component }}"
        fi
      continue-on-error: true
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.component }}-test-results
        path: ${{ matrix.component }}/
